name: goo2d
description: "A modular, low-level 2D game engine for Flutter featuring a component system, physics, advanced rendering, multi-device input, and built-in RPC for networked games."
version: 0.0.2
homepage: https://sunarya-thito.github.io/goo2d/
repository: https://github.com/sunarya-thito/goo2d
issues: https://github.com/sunarya-thito/goo2d/issues

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^4.0.3
  http: ^1.6.0
  meta: ^1.17.0
  vector_math: ^2.1.4
  forge2d: ^0.14.0
  data_widget: ^0.0.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  benchmark_harness: ^2.2.0
  analyzer: ^7.2.0
  glob: ^2.1.2
  path: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

topics:
  - game-engine
  - game-2d
  - game
  - ecs