import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:good_cli/src/assets/options.dart';
import 'package:good_cli/src/assets/pack.dart';
import 'package:test/test.dart';

import 'write_chunk_golden.dart' show goldenKey, goldenMembers;

// The producing half of the format contract. `packages/good` reads the same
// file back with its own implementation; see fixtures/asset_chunk/README.md
// for why neither suite proves anything on its own.

File _golden() {
  final file = File('../../fixtures/asset_chunk/chunk_v1_aes_gzip.dat');
  if (!file.existsSync()) {
    fail(
      'The golden chunk is missing. It is checked in, not generated by the '
      'suite - see fixtures/asset_chunk/README.md.',
    );
  }
  return file;
}

void main() {
  test('the packer still produces the golden chunk, byte for byte', () async {
    final body = buildChunkBody(<String, Uint8List>{
      for (final entry in goldenMembers.entries)
        entry.key: Uint8List.fromList(utf8.encode(entry.value)),
    });
    final sealed = await sealChunk(
      body: body,
      key: goldenKey,
      compression: AssetCompressionLevel.normal,
    );
    expect(
      sealed,
      _golden().readAsBytesSync(),
      reason:
          'good reads this exact file with a separate implementation of the '
          'format. If the layout genuinely changed, bump chunkVersion and '
          'regenerate with test/write_chunk_golden.dart - do not regenerate '
          'to make this pass',
    );
  });

  test('sealing the same body twice gives the same bytes', () async {
    // What made the golden above possible. `GZipEncoder` stamps the clock into
    // its header, so two runs over identical input used to differ - and since
    // the nonce is a hash of the compressed bytes, everything after the header
    // differed with it. A build tool whose output changes when nothing changed
    // cannot answer "did this rebuild produce anything new".
    Future<Uint8List> seal() => sealChunk(
      body: buildChunkBody(<String, Uint8List>{
        'assets/a.webp': Uint8List.fromList(utf8.encode('texture bytes')),
      }),
      key: goldenKey,
      compression: AssetCompressionLevel.normal,
    );
    expect(await seal(), await seal());
  });

  test('and reads its own golden back', () async {
    // Not the interesting direction - good_cli agreeing with itself is what
    // the golden exists to stop being the whole test - but a failure here
    // narrows a golden mismatch to the writer rather than the reader.
    final members = readChunkBody(
      await openChunk(sealed: _golden().readAsBytesSync(), key: goldenKey),
    );
    expect(members.keys, goldenMembers.keys);
    for (final entry in goldenMembers.entries) {
      expect(utf8.decode(members[entry.key]!), entry.value);
    }
  });
}
