/// ECS-facing Box2D physics for `goo2d`.
///
/// Add `RigidBody2D` to a prefab beside `Transform2D` (and usually
/// `Collider2D`), declare a [Box2DPhysicsSystem], and entities simulate:
///
/// ```dart
/// class Crate extends EntityStruct
///     with Transform2D, WorldTransform2D, Collider2D, RigidBody2D {
///   final box = ColliderBody.box(halfWidth: 0.5, halfHeight: 0.5, friction: 0.4);
/// }
/// ```
///
/// A crate is dynamic because that is where `RigidBody2D` starts. Something
/// that should not move says so by moving one column default in its own
/// `describeStruct`:
///
/// ```dart
/// bodyType.initialValue = BodyType2D.staticBody;
/// ```
///
/// The shapes themselves are declared through `goo2d`'s existing
/// `Collider2D`, not through anything here - a collider is a description of
/// an entity's geometry whether or not it is ever simulated, so it belongs in
/// the engine and not in a backend package. This package adds the body
/// (mass, velocity, damping) and the system that steps them.
///
/// ## Units
///
/// Box2D is tuned for **metres, kilograms and seconds**, and works best with
/// moving objects between roughly 0.1 and 10 metres. A game that treats one
/// world unit as one pixel will have a 32-pixel crate acting like a 32-metre
/// building - technically simulated, and visibly wrong. Pick a pixels-per-
/// metre scale and apply it in the camera or the sprite sizes, not in the
/// physics.
///
/// ## Transform authority
///
/// Per body type, and it matters - see `RigidBody2D`'s class doc. Dart owns
/// static and kinematic bodies; Box2D owns dynamic ones. Writing a dynamic
/// body's `Transform2D` every tick fights the solver.
///
/// ## Joints and effectors
///
/// All nine of Unity's 2D joints are here, on [Box2DPhysicsSystem]:
/// distance (and distance-with-spring, Unity's Spring Joint), revolute
/// (Hinge), prismatic (Slider), weld (Fixed), wheel, mouse (Target) and
/// motor - which covers both Relative and Friction, since the difference is
/// only what you ask it to hold.
///
/// **Box2D has no effectors** - Unity's are gameplay code that finds bodies in
/// a region and applies a force - so this package supplies them two ways.
/// Declare one with [Effector2D] and `Effector.area` and the physics
/// system walks it before each step, which is the better default. `Effectors2D`
/// exposes the same four as one-shot calls for a region computed per tick.
/// Area, Point, Buoyancy and Surface are there; Platform (one-way) is not, and
/// `src/effectors.dart` says why.
library;

export 'src/effector.dart'
    show
        AreaEffector,
        BuoyancyEffector,
        Effector,
        Effector2D,
        PointEffector,
        SurfaceEffector;
export 'src/effectors.dart' show Effectors2D;
export 'src/joint.dart' show Joint;
export 'src/physics_system.dart' show Box2DPhysicsSystem;
export 'src/rigid_body.dart' show BodyType2D, RigidBody2D;

// The accessor properties, generated by `good_tool` and committed. One
// extension per component in this package, a getter and a setter per column:
// `entity<Transform2D>().offsetX`. Exported here by hand rather than by the
// generator, because a generator editing a hand-written file is one that can
// lose somebody's edit - `good_tool --check` fails if this line goes missing.
export 'src/accessors.g.dart';

// The component-bit table, generated by `good_tool` and committed (#18). Every
// component type this package registers, in the order their bits are assigned.
// A game names it to `Game.componentBits` to have those bits fixed at build
// time instead of on first sighting, which is what lets a query signature mean
// the same thing in two processes. Exported by hand for the same reason the
// line above is.
export 'src/component_bits.g.dart';

// The declaration collectors, generated by `good_tool` and committed (#353).
// One function per class this package can instantiate that declares anything,
// reading those declarations off an instance in the order its own field
// initialisers would have run. A game names it to `Game.declarations` so a
// registration can read what a constructed object declared. Exported by hand
// for the same reason the line above is.
export 'src/declarations.g.dart';
