import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';
import 'package:goo_cli/src/generate/assets.dart';
import 'package:path/path.dart' as p;
import 'package:meta/meta.dart';

/// Which scene declares which assets.
@immutable
class SceneUsage {
  const SceneUsage({required this.byScene, required this.unresolved});

  /// Scene name -> the logical asset paths it declares, its prefabs included.
  final Map<String, Set<String>> byScene;

  /// `descriptor.has(...)` calls whose argument could not be read statically,
  /// as `where -> what it looked like`.
  ///
  /// Reported rather than ignored, and the reason matters: an asset this pass
  /// cannot attribute must land in the shared chunk, never be dropped. A
  /// grouping that silently loses an asset produces a build that fails to load
  /// it, which is far worse than one that reads an extra chunk.
  final Map<String, String> unresolved;

  bool get isEmpty => byScene.isEmpty;
}

/// Reads a project's Dart and works out which scene needs which asset.
///
/// # Why this needs the analyzer and not a regex
///
/// A scene's asset set is not written in one place. `SceneStruct.describeAssets`
/// declares what the scene itself needs; `describeScene` registers prefabs, and
/// each prefab's own `describeAssets` adds to the same set. Following that
/// means resolving `descriptor.has(Player())` to the `Player` class and reading
/// *its* declarations - which is a type resolution, not a text match. Scenes
/// also arrive as mixins (`mixin FieldScene on SceneStruct`), so "is this a
/// scene" is a supertype question.
///
/// # What it cannot see, and what happens then
///
/// Only statically written declarations. `descriptor.has(Textures.player)` is
/// readable; `descriptor.has(keys[i])` or a key built at run time is not. Those
/// land in [SceneUsage.unresolved] and their assets go to the shared chunk,
/// because being read from one chunk too many is a cost and being absent is a
/// bug.
SceneUsage scanScenes(Directory projectDir, AssetScan assets) {
  final lib = Directory('${projectDir.path}/lib');
  if (!lib.existsSync()) {
    return const SceneUsage(
      byScene: <String, Set<String>>{},
      unresolved: <String, String>{},
    );
  }

  // Identifier -> logical path, per generated enum. `Textures.planePlayerBlue`
  // is resolved by matching the enum's name to the kind and the member's name
  // to the identifier codegen produced - the two halves are generated by the
  // same run, so they cannot drift.
  final byEnum = <String, Map<String, String>>{
    'Textures': <String, String>{
      for (final asset in assets.textures) asset.identifier: asset.path,
    },
    'Audios': <String, String>{
      for (final asset in assets.audio) asset.identifier: asset.path,
    },
  };

  // Normalised with the OS separator: the analyzer refuses anything else, and
  // on Windows `Directory.path` hands back forward slashes that look absolute
  // and are not accepted.
  final collection = AnalysisContextCollection(
    includedPaths: <String>[p.normalize(p.absolute(lib.path))],
  );

  final declarers = <String, _Declarer>{};
  for (final context in collection.contexts) {
    for (final path in context.contextRoot.analyzedFiles()) {
      if (!path.endsWith('.dart')) continue;
      final unit = context.currentSession.getParsedUnit(path);
      if (unit is! ParsedUnitResult) continue;
      final visitor = _DeclarerVisitor(byEnum);
      unit.unit.accept(visitor);
      declarers.addAll(visitor.declarers);
    }
  }

  // Resolve prefab references now that every declaration has been seen: a
  // scene may register a prefab declared in a file read later.
  final byScene = <String, Set<String>>{};
  final unresolved = <String, String>{};
  for (final declarer in declarers.values) {
    unresolved.addAll(declarer.unresolved);
    if (!declarer.isScene) continue;
    final assetsForScene = <String>{};
    _collect(declarer, declarers, assetsForScene, <String>{});
    byScene[declarer.name] = assetsForScene;
  }

  return SceneUsage(byScene: byScene, unresolved: unresolved);
}

/// Walks a declarer and everything it registers, gathering asset paths.
///
/// [seen] guards against a prefab that registers itself, directly or through a
/// cycle - which would otherwise be an infinite descent rather than a build
/// error.
void _collect(
  _Declarer declarer,
  Map<String, _Declarer> all,
  Set<String> into,
  Set<String> seen,
) {
  if (!seen.add(declarer.name)) return;
  into.addAll(declarer.assets);
  for (final name in declarer.registers) {
    final child = all[name];
    if (child != null) _collect(child, all, into, seen);
  }
  for (final name in declarer.mixes) {
    final mixin = all[name];
    if (mixin != null) _collect(mixin, all, into, seen);
  }
}

/// One class or mixin that can declare assets.
class _Declarer {
  _Declarer(this.name, {required this.isScene});

  final String name;

  /// Whether this is a scene rather than a prefab or a plain mixin.
  ///
  /// Decided syntactically - `extends SceneStruct`, `on SceneStruct`, or a
  /// mixin the class applies - because a parsed unit has no element model. A
  /// scene reached only through a chain of intermediate base classes is the
  /// case this misses; see the class doc for why that is acceptable here.
  bool isScene;

  final Set<String> assets = <String>{};

  /// Prefabs registered via `descriptor.has(Prefab())`.
  final Set<String> registers = <String>{};

  /// Mixins applied with `with`, since a scene's assets are often declared in
  /// one - `mixin FieldScene on SceneStruct`.
  final Set<String> mixes = <String>{};

  final Map<String, String> unresolved = <String, String>{};
}

/// Finds declarers and the `has` calls inside them.
///
/// Parsed, not resolved. Resolution would need every dependency's summary and
/// a `pub get` in the target project, and would take seconds per run; the
/// shapes that matter here - `extends SceneStruct`, `with FieldScene`,
/// `descriptor.has(Textures.x)`, `descriptor.has(Player())` - are all
/// syntactic. What that costs is listed on [scanScenes].
class _DeclarerVisitor extends RecursiveAstVisitor<void> {
  _DeclarerVisitor(this._byEnum);

  final Map<String, Map<String, String>> _byEnum;
  final Map<String, _Declarer> declarers = <String, _Declarer>{};

  @override
  void visitClassDeclaration(ClassDeclaration node) {
    final name = node.name.lexeme;
    final superName = node.extendsClause?.superclass.name2.lexeme;
    final mixins = <String>[
      for (final type in node.withClause?.mixinTypes ?? const <NamedType>[])
        type.name2.lexeme,
    ];
    final declarer = _Declarer(
      name,
      isScene: superName == 'SceneStruct' || superName == 'GameSceneStub',
    )..mixes.addAll(mixins);
    declarers[name] = declarer;
    _readBody(node.members, declarer);
    super.visitClassDeclaration(node);
  }

  @override
  void visitMixinDeclaration(MixinDeclaration node) {
    final name = node.name.lexeme;
    final constraints = <String>[
      for (final type
          in node.onClause?.superclassConstraints ?? const <NamedType>[])
        type.name2.lexeme,
    ];
    // `mixin FieldScene on SceneStruct` *is* a scene's asset declaration, and
    // is how penguincivilwar writes one - so a mixin constrained to
    // SceneStruct counts, and a class applying it inherits its assets through
    // `mixes`.
    final declarer = _Declarer(
      name,
      isScene: constraints.contains('SceneStruct'),
    );
    declarers[name] = declarer;
    _readBody(node.members, declarer);
    super.visitMixinDeclaration(node);
  }

  void _readBody(List<ClassMember> members, _Declarer declarer) {
    for (final member in members) {
      if (member is! MethodDeclaration) continue;
      final method = member.name.lexeme;
      if (method != 'describeAssets' && method != 'describeScene') continue;
      member.body.accept(_HasVisitor(declarer, _byEnum, method));
    }
  }
}

/// Collects `descriptor.has(...)` arguments inside one method body.
class _HasVisitor extends RecursiveAstVisitor<void> {
  _HasVisitor(this._declarer, this._byEnum, this._method);

  final _Declarer _declarer;
  final Map<String, Map<String, String>> _byEnum;
  final String _method;

  @override
  void visitMethodInvocation(MethodInvocation node) {
    if (node.methodName.name == 'has' &&
        node.argumentList.arguments.isNotEmpty) {
      final argument = node.argumentList.arguments.first;
      if (_method == 'describeScene') {
        // `descriptor.has(Player())` - the prefab's own describeAssets is
        // walked separately and folded in by `_collect`.
        //
        // Two shapes, because this unit is parsed and not resolved: without
        // resolution the parser cannot tell a constructor call from a function
        // call, so `Player()` arrives as a MethodInvocation and only an
        // explicit `new Player()` is an InstanceCreationExpression. The
        // uppercase-initial name is what separates them, which is a
        // convention rather than a rule - but it is a lint-enforced one, and
        // the cost of guessing wrong is an asset in the shared chunk rather
        // than a wrong build.
        final type = _constructedTypeName(argument);
        if (type != null) {
          _declarer.registers.add(type);
        } else {
          _declarer.unresolved['${_declarer.name}.describeScene'] = '$argument';
        }
      } else if (argument is PrefixedIdentifier) {
        // `Textures.planePlayerBlue`
        final path = _byEnum[argument.prefix.name]?[argument.identifier.name];
        if (path != null) {
          _declarer.assets.add(path);
        } else {
          _declarer.unresolved['${_declarer.name}.describeAssets'] =
              '$argument';
        }
      } else {
        _declarer.unresolved['${_declarer.name}.describeAssets'] = '$argument';
      }
    }
    super.visitMethodInvocation(node);
  }
}

/// The type name [argument] constructs, or null if it does not look like a
/// constructor call.
///
/// `Player()` and `new Player()` both count. The first arrives as a
/// `MethodInvocation` because a parsed unit has no resolution to tell a
/// constructor from a function, so the initial capital is what distinguishes
/// them - Dart's own lints enforce that convention, and a false negative here
/// costs one asset a place in the shared chunk rather than correctness.
String? _constructedTypeName(Expression argument) {
  if (argument is InstanceCreationExpression) {
    return argument.constructorName.type.name2.lexeme;
  }
  if (argument is MethodInvocation && argument.target == null) {
    final name = argument.methodName.name;
    final first = name.isEmpty ? '' : name.substring(0, 1);
    if (first == first.toUpperCase() && first != first.toLowerCase()) {
      return name;
    }
  }
  return null;
}
