/// The 3D good engine.
///
/// **One dependency, one import.** Adding `goo3d` to a pubspec and importing
/// this library gives you the kernel (ECS, scenes, the tick loop,
/// `Game`/`GameState`, `GameView`) *and* the 3D layer. The kernel is
/// re-exported below, so it is not a second dependency you add and keep
/// version-matched by hand. `goo2d` is arranged the same way.
///
/// **There is no renderer here yet.** This library is transforms, hierarchy
/// composition and the camera - the maths and columns everything above them
/// stands on. Meshes, materials, lights and the draw path are issue #43, a
/// native backend behind a C shim, and nothing here pretends to stand in for
/// it.
library;

export 'package:good/good.dart';

export 'src/data/camera.dart';
export 'src/data/transform.dart';
export 'src/data/world_transform.dart';

// The accessor properties, generated by `good_tool` and committed. One
// extension per component in this package, a getter and a setter per column:
// `entity<Transform2D>().offsetX`. Exported here by hand rather than by the
// generator, because a generator editing a hand-written file is one that can
// lose somebody's edit - `good_tool --check` fails if this line goes missing.
export 'src/accessors.g.dart';
