// GENERATED FILE - DO NOT EDIT.
//
// Regenerate with:
//   dart run ffigen --config ffigen.yaml
//
// ignore_for_file: always_specify_types, camel_case_types
// ignore_for_file: non_constant_identifier_names, public_member_api_docs
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated bindings to the goo2d Box2D shim (src/goo_box2d.h).
///
/// Do not edit by hand - regenerate with ffigen. See ffigen.yaml.
///
class Box2DBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Box2DBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Box2DBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Box2D's version, packed as (major << 16) | (minor << 8) | revision.
  /// The Dart loader asserts against this so a stale prebuilt library on
  /// the library search path fails loudly at boot instead of subtly at
  /// the first step.
  int gooB2Version() {
    return _gooB2Version();
  }

  late final _gooB2VersionPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('gooB2Version');
  late final _gooB2Version = _gooB2VersionPtr.asFunction<int Function()>();

  /// Creates a world with the given gravity. Returns a packed world
  /// handle, or 0 on failure.
  int gooWorldCreate(
    double gravityX,
    double gravityY,
  ) {
    return _gooWorldCreate(
      gravityX,
      gravityY,
    );
  }

  late final _gooWorldCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Float, ffi.Float)>>(
          'gooWorldCreate');
  late final _gooWorldCreate =
      _gooWorldCreatePtr.asFunction<int Function(double, double)>();

  /// A world that steps across [workerCount] threads.
  ///
  /// Box2D does not create threads; this hands it a pool that does, through
  /// `enqueueTask`/`finishTask`. A [workerCount] of 1 or less is exactly
  /// [gooWorldCreate] - no pool, no threads, no behavioural difference.
  ///
  /// **The pool belongs to the world and is destroyed with it**, so a caller
  /// has one lifetime to think about rather than two. That is why this is a
  /// separate constructor instead of a setter: a world cannot change its
  /// worker count, and a pool cannot outlive its world.
  ///
  /// Box2D warns that only performance cores help - efficiency cores and
  /// hyper-threading "provide little benefit and may even harm performance"
  /// - so more workers than physical cores is usually slower, not faster.
  int gooWorldCreateThreaded(
    double gravityX,
    double gravityY,
    int workerCount,
  ) {
    return _gooWorldCreateThreaded(
      gravityX,
      gravityY,
      workerCount,
    );
  }

  late final _gooWorldCreateThreadedPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int64 Function(ffi.Float, ffi.Float, ffi.Int32)>>(
      'gooWorldCreateThreaded');
  late final _gooWorldCreateThreaded = _gooWorldCreateThreadedPtr
      .asFunction<int Function(double, double, int)>();

  /// How many workers [world] was created with; 1 for a single-threaded one.
  int gooWorldWorkerCount(
    int world,
  ) {
    return _gooWorldWorkerCount(
      world,
    );
  }

  late final _gooWorldWorkerCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooWorldWorkerCount');
  late final _gooWorldWorkerCount =
      _gooWorldWorkerCountPtr.asFunction<int Function(int)>();

  void gooWorldDestroy(
    int world,
  ) {
    return _gooWorldDestroy(
      world,
    );
  }

  late final _gooWorldDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'gooWorldDestroy');
  late final _gooWorldDestroy =
      _gooWorldDestroyPtr.asFunction<void Function(int)>();

  /// Advances the world by `timeStep` seconds. `subStepCount` is Box2D's
  /// solver iteration count; 4 is its own recommended default.
  void gooWorldStep(
    int world,
    double timeStep,
    int subStepCount,
  ) {
    return _gooWorldStep(
      world,
      timeStep,
      subStepCount,
    );
  }

  late final _gooWorldStepPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Float, ffi.Int32)>>('gooWorldStep');
  late final _gooWorldStep =
      _gooWorldStepPtr.asFunction<void Function(int, double, int)>();

  /// `type` is 0 static, 1 kinematic, 2 dynamic - Box2D's own b2BodyType
  /// values, asserted to match in goo_box2d.c so the Dart enum cannot
  /// drift from the C one silently.
  int gooBodyCreate(
    int world,
    int type,
    double x,
    double y,
    double angle,
  ) {
    return _gooBodyCreate(
      world,
      type,
      x,
      y,
      angle,
    );
  }

  late final _gooBodyCreatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(ffi.Int64, ffi.Int32, ffi.Float, ffi.Float,
              ffi.Float)>>('gooBodyCreate');
  late final _gooBodyCreate = _gooBodyCreatePtr
      .asFunction<int Function(int, int, double, double, double)>();

  void gooBodyDestroy(
    int body,
  ) {
    return _gooBodyDestroy(
      body,
    );
  }

  late final _gooBodyDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'gooBodyDestroy');
  late final _gooBodyDestroy =
      _gooBodyDestroyPtr.asFunction<void Function(int)>();

  /// Removes the body from simulation without destroying it, keeping its
  /// handle valid. This is how a whole entity's physics goes inert;
  /// disabling one shape of several is gooShapeSetFilter with a zero mask.
  void gooBodySetEnabled(
    int body,
    int enabled,
  ) {
    return _gooBodySetEnabled(
      body,
      enabled,
    );
  }

  late final _gooBodySetEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooBodySetEnabled');
  late final _gooBodySetEnabled =
      _gooBodySetEnabledPtr.asFunction<void Function(int, int)>();

  /// Whether the handle still resolves to a live body. Box2D's ids carry
  /// a generation counter, so this correctly reports false for a stale
  /// handle whose slot has been reused - the same problem `Scene` solves
  /// with its own generation field.
  int gooBodyIsValid(
    int body,
  ) {
    return _gooBodyIsValid(
      body,
    );
  }

  late final _gooBodyIsValidPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooBodyIsValid');
  late final _gooBodyIsValid =
      _gooBodyIsValidPtr.asFunction<int Function(int)>();

  void gooBodySetTransform(
    int body,
    double x,
    double y,
    double angle,
  ) {
    return _gooBodySetTransform(
      body,
      x,
      y,
      angle,
    );
  }

  late final _gooBodySetTransformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float,
              ffi.Float)>>('gooBodySetTransform');
  late final _gooBodySetTransform = _gooBodySetTransformPtr
      .asFunction<void Function(int, double, double, double)>();

  /// Writes {x, y, angle} into `outXya` (3 floats).
  void gooBodyGetTransform(
    int body,
    ffi.Pointer<ffi.Float> outXya,
  ) {
    return _gooBodyGetTransform(
      body,
      outXya,
    );
  }

  late final _gooBodyGetTransformPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<ffi.Float>)>>('gooBodyGetTransform');
  late final _gooBodyGetTransform = _gooBodyGetTransformPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Float>)>();

  void gooBodySetLinearVelocity(
    int body,
    double vx,
    double vy,
  ) {
    return _gooBodySetLinearVelocity(
      body,
      vx,
      vy,
    );
  }

  late final _gooBodySetLinearVelocityPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float)>>(
      'gooBodySetLinearVelocity');
  late final _gooBodySetLinearVelocity = _gooBodySetLinearVelocityPtr
      .asFunction<void Function(int, double, double)>();

  void gooBodySetAngularVelocity(
    int body,
    double w,
  ) {
    return _gooBodySetAngularVelocity(
      body,
      w,
    );
  }

  late final _gooBodySetAngularVelocityPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'gooBodySetAngularVelocity');
  late final _gooBodySetAngularVelocity =
      _gooBodySetAngularVelocityPtr.asFunction<void Function(int, double)>();

  /// Writes {vx, vy, w} into `outVel` (3 floats).
  void gooBodyGetVelocity(
    int body,
    ffi.Pointer<ffi.Float> outVel,
  ) {
    return _gooBodyGetVelocity(
      body,
      outVel,
    );
  }

  late final _gooBodyGetVelocityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<ffi.Float>)>>('gooBodyGetVelocity');
  late final _gooBodyGetVelocity = _gooBodyGetVelocityPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Float>)>();

  void gooBodySetGravityScale(
    int body,
    double scale,
  ) {
    return _gooBodySetGravityScale(
      body,
      scale,
    );
  }

  late final _gooBodySetGravityScalePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float)>>(
          'gooBodySetGravityScale');
  late final _gooBodySetGravityScale =
      _gooBodySetGravityScalePtr.asFunction<void Function(int, double)>();

  void gooBodySetDamping(
    int body,
    double linear,
    double angular,
  ) {
    return _gooBodySetDamping(
      body,
      linear,
      angular,
    );
  }

  late final _gooBodySetDampingPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float)>>(
      'gooBodySetDamping');
  late final _gooBodySetDamping =
      _gooBodySetDampingPtr.asFunction<void Function(int, double, double)>();

  void gooBodySetFixedRotation(
    int body,
    int fixed,
  ) {
    return _gooBodySetFixedRotation(
      body,
      fixed,
    );
  }

  late final _gooBodySetFixedRotationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooBodySetFixedRotation');
  late final _gooBodySetFixedRotation =
      _gooBodySetFixedRotationPtr.asFunction<void Function(int, int)>();

  void gooBodySetBullet(
    int body,
    int bullet,
  ) {
    return _gooBodySetBullet(
      body,
      bullet,
    );
  }

  late final _gooBodySetBulletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooBodySetBullet');
  late final _gooBodySetBullet =
      _gooBodySetBulletPtr.asFunction<void Function(int, int)>();

  void gooBodySetType(
    int body,
    int type,
  ) {
    return _gooBodySetType(
      body,
      type,
    );
  }

  late final _gooBodySetTypePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooBodySetType');
  late final _gooBodySetType =
      _gooBodySetTypePtr.asFunction<void Function(int, int)>();

  void gooBodyApplyForce(
    int body,
    double fx,
    double fy,
    int wake,
  ) {
    return _gooBodyApplyForce(
      body,
      fx,
      fy,
      wake,
    );
  }

  late final _gooBodyApplyForcePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float,
              ffi.Int32)>>('gooBodyApplyForce');
  late final _gooBodyApplyForce = _gooBodyApplyForcePtr
      .asFunction<void Function(int, double, double, int)>();

  void gooBodyApplyImpulse(
    int body,
    double ix,
    double iy,
    int wake,
  ) {
    return _gooBodyApplyImpulse(
      body,
      ix,
      iy,
      wake,
    );
  }

  late final _gooBodyApplyImpulsePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float,
              ffi.Int32)>>('gooBodyApplyImpulse');
  late final _gooBodyApplyImpulse = _gooBodyApplyImpulsePtr
      .asFunction<void Function(int, double, double, int)>();

  void gooBodyApplyTorque(
    int body,
    double torque,
    int wake,
  ) {
    return _gooBodyApplyTorque(
      body,
      torque,
      wake,
    );
  }

  late final _gooBodyApplyTorquePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float, ffi.Int32)>>(
      'gooBodyApplyTorque');
  late final _gooBodyApplyTorque =
      _gooBodyApplyTorquePtr.asFunction<void Function(int, double, int)>();

  /// --- shapes ------------------------------------------------------------
  ///
  /// One entry point per goo2d ColliderBody subtype. They share a trailing
  /// material/filter parameter block rather than a struct, because a struct
  /// is exactly what this header exists to avoid.
  ///
  /// `category` and `mask` are Box2D's b2Filter bits, which are uint64_t in
  /// v3.1.1 - wide enough for goo2d's `layer` (a bit index) across all 64
  /// layers. `isSensor` maps goo2d's `isTrigger`.
  int gooShapeAddCircle(
    int body,
    double cx,
    double cy,
    double radius,
    double density,
    double friction,
    double restitution,
    int category,
    int mask,
    int isSensor,
  ) {
    return _gooShapeAddCircle(
      body,
      cx,
      cy,
      radius,
      density,
      friction,
      restitution,
      category,
      mask,
      isSensor,
    );
  }

  late final _gooShapeAddCirclePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Int32)>>('gooShapeAddCircle');
  late final _gooShapeAddCircle = _gooShapeAddCirclePtr.asFunction<
      int Function(int, double, double, double, double, double, double, int,
          int, int)>();

  int gooShapeAddBox(
    int body,
    double cx,
    double cy,
    double halfWidth,
    double halfHeight,
    double angle,
    double density,
    double friction,
    double restitution,
    int category,
    int mask,
    int isSensor,
  ) {
    return _gooShapeAddBox(
      body,
      cx,
      cy,
      halfWidth,
      halfHeight,
      angle,
      density,
      friction,
      restitution,
      category,
      mask,
      isSensor,
    );
  }

  late final _gooShapeAddBoxPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Int32)>>('gooShapeAddBox');
  late final _gooShapeAddBox = _gooShapeAddBoxPtr.asFunction<
      int Function(int, double, double, double, double, double, double, double,
          double, int, int, int)>();

  /// A capsule standing on its y axis, matching goo2d's CapsuleBody:
  /// `halfHeight` is half the TOTAL height, caps included (Unity's
  /// CapsuleCollider2D.size semantics), so the straight section runs
  /// +/- (halfHeight - radius). A capsule shorter than it is wide
  /// degenerates to a circle rather than erroring - the same choice
  /// CapsuleBody.containsLocalPoint already makes.
  int gooShapeAddCapsule(
    int body,
    double cx,
    double cy,
    double radius,
    double halfHeight,
    double density,
    double friction,
    double restitution,
    int category,
    int mask,
    int isSensor,
  ) {
    return _gooShapeAddCapsule(
      body,
      cx,
      cy,
      radius,
      halfHeight,
      density,
      friction,
      restitution,
      category,
      mask,
      isSensor,
    );
  }

  late final _gooShapeAddCapsulePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Int32)>>('gooShapeAddCapsule');
  late final _gooShapeAddCapsule = _gooShapeAddCapsulePtr.asFunction<
      int Function(int, double, double, double, double, double, double, double,
          int, int, int)>();

  /// `pointsXy` is `count` interleaved x,y pairs (2 * count floats) in
  /// body-local space, already offset by the caller. Returns 0 if Box2D's
  /// hull builder rejects the points (fewer than 3, collinear, or beyond
  /// B2_MAX_POLYGON_VERTICES) rather than creating a degenerate shape.
  int gooShapeAddPolygon(
    int body,
    ffi.Pointer<ffi.Float> pointsXy,
    int count,
    double density,
    double friction,
    double restitution,
    int category,
    int mask,
    int isSensor,
  ) {
    return _gooShapeAddPolygon(
      body,
      pointsXy,
      count,
      density,
      friction,
      restitution,
      category,
      mask,
      isSensor,
    );
  }

  late final _gooShapeAddPolygonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Pointer<ffi.Float>,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Int32)>>('gooShapeAddPolygon');
  late final _gooShapeAddPolygon = _gooShapeAddPolygonPtr.asFunction<
      int Function(int, ffi.Pointer<ffi.Float>, int, double, double, double,
          int, int, int)>();

  int gooShapeGetBody(
    int shape,
  ) {
    return _gooShapeGetBody(
      shape,
    );
  }

  late final _gooShapeGetBodyPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Int64)>>(
          'gooShapeGetBody');
  late final _gooShapeGetBody =
      _gooShapeGetBodyPtr.asFunction<int Function(int)>();

  void gooShapeDestroy(
    int shape,
    int updateBodyMass,
  ) {
    return _gooShapeDestroy(
      shape,
      updateBodyMass,
    );
  }

  late final _gooShapeDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooShapeDestroy');
  late final _gooShapeDestroy =
      _gooShapeDestroyPtr.asFunction<void Function(int, int)>();

  /// Box2D v3 has no per-shape enable flag, so goo2d's
  /// `ColliderBody.enable` is expressed as a filter change: a zero mask
  /// collides with nothing. Dart passes both bits every time rather than
  /// this shim remembering a "real" mask to restore - the authoritative
  /// `layer`/`excludeLayers` already live in component storage, and
  /// caching a second copy here is the drift RULES.md rule 10 describes.
  void gooShapeSetFilter(
    int shape,
    int category,
    int mask,
  ) {
    return _gooShapeSetFilter(
      shape,
      category,
      mask,
    );
  }

  late final _gooShapeSetFilterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Uint64, ffi.Uint64)>>('gooShapeSetFilter');
  late final _gooShapeSetFilter =
      _gooShapeSetFilterPtr.asFunction<void Function(int, int, int)>();

  /// Landing 4 needs these on to receive anything from
  /// b2World_GetContactEvents / GetSensorEvents.
  void gooShapeEnableContactEvents(
    int shape,
    int flag,
  ) {
    return _gooShapeEnableContactEvents(
      shape,
      flag,
    );
  }

  late final _gooShapeEnableContactEventsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooShapeEnableContactEvents');
  late final _gooShapeEnableContactEvents =
      _gooShapeEnableContactEventsPtr.asFunction<void Function(int, int)>();

  void gooShapeEnableSensorEvents(
    int shape,
    int flag,
  ) {
    return _gooShapeEnableSensorEvents(
      shape,
      flag,
    );
  }

  late final _gooShapeEnableSensorEventsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32)>>(
          'gooShapeEnableSensorEvents');
  late final _gooShapeEnableSensorEvents =
      _gooShapeEnableSensorEventsPtr.asFunction<void Function(int, int)>();

  /// Pushes `count` transforms into the world. `bodies` is `count` packed
  /// handles; `xya` is 3 floats per body. A zero or stale handle is
  /// skipped, so a caller need not compact its arrays when an entity dies
  /// mid-tick.
  void gooBodiesPushTransforms(
    ffi.Pointer<ffi.Int64> bodies,
    ffi.Pointer<ffi.Float> xya,
    int count,
  ) {
    return _gooBodiesPushTransforms(
      bodies,
      xya,
      count,
    );
  }

  late final _gooBodiesPushTransformsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>,
              ffi.Int32)>>('gooBodiesPushTransforms');
  late final _gooBodiesPushTransforms = _gooBodiesPushTransformsPtr.asFunction<
      void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>, int)>();

  /// The reverse: reads `count` transforms out into `outXya` (3 floats
  /// per body). A skipped body leaves its 3 slots untouched, so the
  /// caller's previous values survive rather than becoming zeros.
  void gooBodiesPullTransforms(
    ffi.Pointer<ffi.Int64> bodies,
    ffi.Pointer<ffi.Float> outXya,
    int count,
  ) {
    return _gooBodiesPullTransforms(
      bodies,
      outXya,
      count,
    );
  }

  late final _gooBodiesPullTransformsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>,
              ffi.Int32)>>('gooBodiesPullTransforms');
  late final _gooBodiesPullTransforms = _gooBodiesPullTransformsPtr.asFunction<
      void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>, int)>();

  /// Velocities alongside the transforms, same skipping rules, 3 floats
  /// per body ({vx, vy, w}).
  void gooBodiesPushVelocities(
    ffi.Pointer<ffi.Int64> bodies,
    ffi.Pointer<ffi.Float> vel,
    int count,
  ) {
    return _gooBodiesPushVelocities(
      bodies,
      vel,
      count,
    );
  }

  late final _gooBodiesPushVelocitiesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>,
              ffi.Int32)>>('gooBodiesPushVelocities');
  late final _gooBodiesPushVelocities = _gooBodiesPushVelocitiesPtr.asFunction<
      void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>, int)>();

  void gooBodiesPullVelocities(
    ffi.Pointer<ffi.Int64> bodies,
    ffi.Pointer<ffi.Float> outVel,
    int count,
  ) {
    return _gooBodiesPullVelocities(
      bodies,
      outVel,
      count,
    );
  }

  late final _gooBodiesPullVelocitiesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>,
              ffi.Int32)>>('gooBodiesPullVelocities');
  late final _gooBodiesPullVelocities = _gooBodiesPullVelocitiesPtr.asFunction<
      void Function(ffi.Pointer<ffi.Int64>, ffi.Pointer<ffi.Float>, int)>();

  /// Drains this step's contact (non-sensor) touch transitions.
  ///
  /// `shapeA`/`shapeB` are packed shape handles. Events beyond `maxEvents`
  /// are **dropped**, and the caller is expected to size its buffer from
  /// the previous tick's return value rather than have this grow one.
  int gooWorldDrainContacts(
    int world,
    ffi.Pointer<ffi.Int64> out,
    int maxEvents,
  ) {
    return _gooWorldDrainContacts(
      world,
      out,
      maxEvents,
    );
  }

  late final _gooWorldDrainContactsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Int64, ffi.Pointer<ffi.Int64>,
              ffi.Int32)>>('gooWorldDrainContacts');
  late final _gooWorldDrainContacts = _gooWorldDrainContactsPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Int64>, int)>();

  /// Drains this step's sensor touch transitions. `shapeA` is the sensor,
  /// `shapeB` the visitor - an order Box2D itself guarantees, which is what
  /// lets goo2d report a trigger event without asking which side was which.
  int gooWorldDrainSensors(
    int world,
    ffi.Pointer<ffi.Int64> out,
    int maxEvents,
  ) {
    return _gooWorldDrainSensors(
      world,
      out,
      maxEvents,
    );
  }

  late final _gooWorldDrainSensorsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Int64, ffi.Pointer<ffi.Int64>,
              ffi.Int32)>>('gooWorldDrainSensors');
  late final _gooWorldDrainSensors = _gooWorldDrainSensorsPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Int64>, int)>();

  /// How many contact and sensor records the last step produced, whether or
  /// not they fitted in the buffer. Lets a caller resize *after* a drain
  /// that overflowed rather than guessing up front.
  int gooWorldContactEventCount(
    int world,
  ) {
    return _gooWorldContactEventCount(
      world,
    );
  }

  late final _gooWorldContactEventCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooWorldContactEventCount');
  late final _gooWorldContactEventCount =
      _gooWorldContactEventCountPtr.asFunction<int Function(int)>();

  int gooWorldSensorEventCount(
    int world,
  ) {
    return _gooWorldSensorEventCount(
      world,
    );
  }

  late final _gooWorldSensorEventCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooWorldSensorEventCount');
  late final _gooWorldSensorEventCount =
      _gooWorldSensorEventCountPtr.asFunction<int Function(int)>();

  /// Creates a distance joint - two points held a fixed distance apart, with
  /// an optional spring and optional length limits. Ropes, springs,
  /// suspension.
  ///
  /// Returns the packed joint handle, or 0 if either body was invalid.
  int gooJointCreateDistance(
    int bodyA,
    int bodyB,
    double ax,
    double ay,
    double bx,
    double by,
    double length,
    int enableSpring,
    double hertz,
    double dampingRatio,
    int enableLimit,
    double minLength,
    double maxLength,
    int collideConnected,
  ) {
    return _gooJointCreateDistance(
      bodyA,
      bodyB,
      ax,
      ay,
      bx,
      by,
      length,
      enableSpring,
      hertz,
      dampingRatio,
      enableLimit,
      minLength,
      maxLength,
      collideConnected,
    );
  }

  late final _gooJointCreateDistancePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateDistance');
  late final _gooJointCreateDistance = _gooJointCreateDistancePtr.asFunction<
      int Function(int, int, double, double, double, double, double, int,
          double, double, int, double, double, int)>();

  /// Creates a revolute joint - two bodies sharing a pivot, with optional
  /// angle limits and an optional motor. Hinges, wheels, ragdoll elbows.
  int gooJointCreateRevolute(
    int bodyA,
    int bodyB,
    double ax,
    double ay,
    double bx,
    double by,
    double referenceAngle,
    int enableLimit,
    double lowerAngle,
    double upperAngle,
    int enableMotor,
    double motorSpeed,
    double maxMotorTorque,
    int collideConnected,
  ) {
    return _gooJointCreateRevolute(
      bodyA,
      bodyB,
      ax,
      ay,
      bx,
      by,
      referenceAngle,
      enableLimit,
      lowerAngle,
      upperAngle,
      enableMotor,
      motorSpeed,
      maxMotorTorque,
      collideConnected,
    );
  }

  late final _gooJointCreateRevolutePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateRevolute');
  late final _gooJointCreateRevolute = _gooJointCreateRevolutePtr.asFunction<
      int Function(int, int, double, double, double, double, double, int,
          double, double, int, double, double, int)>();

  /// Creates a prismatic joint - two bodies sharing one axis of translation,
  /// with optional limits and an optional motor. Unity calls this a Slider
  /// Joint 2D. Lifts, sliding doors, pistons.
  ///
  /// `(axisX, axisY)` is the free axis in **body A's local frame**.
  int gooJointCreatePrismatic(
    int bodyA,
    int bodyB,
    double ax,
    double ay,
    double bx,
    double by,
    double axisX,
    double axisY,
    double referenceAngle,
    int enableLimit,
    double lower,
    double upper,
    int enableMotor,
    double motorSpeed,
    double maxMotorForce,
    int collideConnected,
  ) {
    return _gooJointCreatePrismatic(
      bodyA,
      bodyB,
      ax,
      ay,
      bx,
      by,
      axisX,
      axisY,
      referenceAngle,
      enableLimit,
      lower,
      upper,
      enableMotor,
      motorSpeed,
      maxMotorForce,
      collideConnected,
    );
  }

  late final _gooJointCreatePrismaticPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreatePrismatic');
  late final _gooJointCreatePrismatic = _gooJointCreatePrismaticPtr.asFunction<
      int Function(int, int, double, double, double, double, double, double,
          double, int, double, double, int, double, double, int)>();

  /// Creates a weld joint - two bodies held rigidly together, optionally with
  /// spring give. Unity calls this a Fixed Joint 2D. Breakable structures,
  /// stuck-together debris.
  ///
  /// A hertz of 0 on either axis is a rigid weld; above 0 it is a soft one.
  int gooJointCreateWeld(
    int bodyA,
    int bodyB,
    double ax,
    double ay,
    double bx,
    double by,
    double referenceAngle,
    double linearHertz,
    double linearDampingRatio,
    double angularHertz,
    double angularDampingRatio,
    int collideConnected,
  ) {
    return _gooJointCreateWeld(
      bodyA,
      bodyB,
      ax,
      ay,
      bx,
      by,
      referenceAngle,
      linearHertz,
      linearDampingRatio,
      angularHertz,
      angularDampingRatio,
      collideConnected,
    );
  }

  late final _gooJointCreateWeldPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateWeld');
  late final _gooJointCreateWeld = _gooJointCreateWeldPtr.asFunction<
      int Function(int, int, double, double, double, double, double, double,
          double, double, double, int)>();

  /// Creates a wheel joint - a suspension axis plus a spin. Unity calls this
  /// a Wheel Joint 2D, and it is what a driven vehicle wheel is.
  int gooJointCreateWheel(
    int bodyA,
    int bodyB,
    double ax,
    double ay,
    double bx,
    double by,
    double axisX,
    double axisY,
    int enableSpring,
    double hertz,
    double dampingRatio,
    int enableLimit,
    double lower,
    double upper,
    int enableMotor,
    double motorSpeed,
    double maxMotorTorque,
    int collideConnected,
  ) {
    return _gooJointCreateWheel(
      bodyA,
      bodyB,
      ax,
      ay,
      bx,
      by,
      axisX,
      axisY,
      enableSpring,
      hertz,
      dampingRatio,
      enableLimit,
      lower,
      upper,
      enableMotor,
      motorSpeed,
      maxMotorTorque,
      collideConnected,
    );
  }

  late final _gooJointCreateWheelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateWheel');
  late final _gooJointCreateWheel = _gooJointCreateWheelPtr.asFunction<
      int Function(
          int,
          int,
          double,
          double,
          double,
          double,
          double,
          double,
          int,
          double,
          double,
          int,
          double,
          double,
          int,
          double,
          double,
          int)>();

  /// Creates a motor joint - drives body B to a position and angle relative
  /// to body A. Unity splits this into Relative Joint 2D (drive to an offset)
  /// and Friction Joint 2D (drive to *no* motion, which is what a zero
  /// target with a force cap is).
  int gooJointCreateMotor(
    int bodyA,
    int bodyB,
    double offsetX,
    double offsetY,
    double angularOffset,
    double maxForce,
    double maxTorque,
    double correctionFactor,
    int collideConnected,
  ) {
    return _gooJointCreateMotor(
      bodyA,
      bodyB,
      offsetX,
      offsetY,
      angularOffset,
      maxForce,
      maxTorque,
      correctionFactor,
      collideConnected,
    );
  }

  late final _gooJointCreateMotorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateMotor');
  late final _gooJointCreateMotor = _gooJointCreateMotorPtr.asFunction<
      int Function(
          int, int, double, double, double, double, double, double, int)>();

  /// Creates a mouse joint - drags body B towards a world-space target.
  /// Unity calls this a Target Joint 2D. Mouse dragging, tractor beams.
  ///
  /// The target is world space, not body-local, because that is the whole
  /// point: it is where you want the body to go, not a point on it.
  int gooJointCreateMouse(
    int bodyA,
    int bodyB,
    double targetX,
    double targetY,
    double hertz,
    double dampingRatio,
    double maxForce,
    int collideConnected,
  ) {
    return _gooJointCreateMouse(
      bodyA,
      bodyB,
      targetX,
      targetY,
      hertz,
      dampingRatio,
      maxForce,
      collideConnected,
    );
  }

  late final _gooJointCreateMousePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Int32)>>('gooJointCreateMouse');
  late final _gooJointCreateMouse = _gooJointCreateMousePtr.asFunction<
      int Function(int, int, double, double, double, double, double, int)>();

  /// Moves a mouse joint's world-space target. The one joint parameter that
  /// is expected to change every frame, so it gets its own entry point.
  void gooJointSetMouseTarget(
    int joint,
    double x,
    double y,
  ) {
    return _gooJointSetMouseTarget(
      joint,
      x,
      y,
    );
  }

  late final _gooJointSetMouseTargetPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.Float, ffi.Float)>>(
      'gooJointSetMouseTarget');
  late final _gooJointSetMouseTarget = _gooJointSetMouseTargetPtr
      .asFunction<void Function(int, double, double)>();

  void gooJointDestroy(
    int joint,
  ) {
    return _gooJointDestroy(
      joint,
    );
  }

  late final _gooJointDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'gooJointDestroy');
  late final _gooJointDestroy =
      _gooJointDestroyPtr.asFunction<void Function(int)>();

  /// Whether [joint] still names a live joint. Zero once either of its
  /// bodies has been destroyed, which destroys the joint with it.
  int gooJointIsValid(
    int joint,
  ) {
    return _gooJointIsValid(
      joint,
    );
  }

  late final _gooJointIsValidPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooJointIsValid');
  late final _gooJointIsValid =
      _gooJointIsValidPtr.asFunction<int Function(int)>();

  /// Motor control, shared by both joint types above. `speed` is rad/s for a
  /// revolute joint and m/s for a distance one; `maxEffort` is the torque or
  /// force the motor may use to reach it.
  void gooJointSetMotor(
    int joint,
    int enable,
    double speed,
    double maxEffort,
  ) {
    return _gooJointSetMotor(
      joint,
      enable,
      speed,
      maxEffort,
    );
  }

  late final _gooJointSetMotorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Int32, ffi.Float, ffi.Float)>>('gooJointSetMotor');
  late final _gooJointSetMotor = _gooJointSetMotorPtr
      .asFunction<void Function(int, int, double, double)>();

  /// The force this joint is currently applying, in newtons, written as two
  /// floats (x, y) into `outForce`. Returns the torque, in newton-metres.
  ///
  /// Together these are what a **breakable** joint is built from: compare
  /// against a threshold each tick and destroy the joint when it is
  /// exceeded. Box2D has no breaking of its own.
  double gooJointGetReaction(
    int joint,
    ffi.Pointer<ffi.Float> outForce,
  ) {
    return _gooJointGetReaction(
      joint,
      outForce,
    );
  }

  late final _gooJointGetReactionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Float Function(
              ffi.Int64, ffi.Pointer<ffi.Float>)>>('gooJointGetReaction');
  late final _gooJointGetReaction = _gooJointGetReactionPtr
      .asFunction<double Function(int, ffi.Pointer<ffi.Float>)>();

  /// Bodies Box2D is still integrating. A settled pile sleeps, and a sleeping
  /// body costs almost nothing - so this next to the body count is the
  /// difference between a scene that is heavy and one that is agitated.
  int gooWorldAwakeBodyCount(
    int world,
  ) {
    return _gooWorldAwakeBodyCount(
      world,
    );
  }

  late final _gooWorldAwakeBodyCountPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int64)>>(
          'gooWorldAwakeBodyCount');
  late final _gooWorldAwakeBodyCount =
      _gooWorldAwakeBodyCountPtr.asFunction<int Function(int)>();

  /// Writes `min(count, GOO_COUNTER_COUNT)` int32 counters into `out`:
  ///
  /// [ bodies, shapes, contacts, joints, islands ]
  ///
  /// Flattened into a caller's array rather than returned as `b2Counters`,
  /// which is a struct by value - the one thing this shim exists to keep out
  /// of the Dart bindings.
  ///
  /// **Contacts here are potential (broad-phase) pairs**, not the touching
  /// pairs the event API reports. A pile whose contact count climbs far
  /// faster than its body count is overlapping, not merely large.
  void gooWorldCounters(
    int world,
    ffi.Pointer<ffi.Int32> out,
    int count,
  ) {
    return _gooWorldCounters(
      world,
      out,
      count,
    );
  }

  late final _gooWorldCountersPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Int32>,
              ffi.Int32)>>('gooWorldCounters');
  late final _gooWorldCounters = _gooWorldCountersPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Int32>, int)>();

  /// Casts a ray from (originX, originY) along (dx, dy) - a *translation*,
  /// not a direction, so its length is the ray's length.
  ///
  /// Returns the packed handle of the closest shape hit, or 0 for a miss.
  /// On a hit, writes 5 floats into `outHit`:
  ///
  /// [ pointX, pointY, normalX, normalY, fraction ]
  ///
  /// Split that way because the handle is an integer and the rest are
  /// floats; one mixed buffer would have to be punned on the Dart side.
  /// `outHit` is untouched on a miss.
  int gooWorldCastRayClosest(
    int world,
    double originX,
    double originY,
    double dx,
    double dy,
    int category,
    int mask,
    ffi.Pointer<ffi.Float> outHit,
  ) {
    return _gooWorldCastRayClosest(
      world,
      originX,
      originY,
      dx,
      dy,
      category,
      mask,
      outHit,
    );
  }

  late final _gooWorldCastRayClosestPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int64 Function(
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Float>)>>('gooWorldCastRayClosest');
  late final _gooWorldCastRayClosest = _gooWorldCastRayClosestPtr.asFunction<
      int Function(int, double, double, double, double, int, int,
          ffi.Pointer<ffi.Float>)>();

  /// Collects the shapes whose fat AABB overlaps the given box, writing
  /// packed handles into `outShapes`. Returns how many were written.
  ///
  /// This is a **broad-phase** test: an AABB overlap, not an exact shape
  /// overlap. It is what you want for "roughly what is in this region";
  /// callers needing exactness re-test the survivors themselves.
  ///
  /// Results beyond `maxShapes` are dropped rather than growing anything.
  int gooWorldOverlapAABB(
    int world,
    double minX,
    double minY,
    double maxX,
    double maxY,
    int category,
    int mask,
    ffi.Pointer<ffi.Int64> outShapes,
    int maxShapes,
  ) {
    return _gooWorldOverlapAABB(
      world,
      minX,
      minY,
      maxX,
      maxY,
      category,
      mask,
      outShapes,
      maxShapes,
    );
  }

  late final _gooWorldOverlapAABBPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Int64,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Float,
              ffi.Uint64,
              ffi.Uint64,
              ffi.Pointer<ffi.Int64>,
              ffi.Int32)>>('gooWorldOverlapAABB');
  late final _gooWorldOverlapAABB = _gooWorldOverlapAABBPtr.asFunction<
      int Function(int, double, double, double, double, int, int,
          ffi.Pointer<ffi.Int64>, int)>();
}

const int GOO_TOUCH_BEGIN = 0;

const int GOO_TOUCH_END = 1;

const int GOO_COUNTER_COUNT = 5;
