name: goo2d_example
description: "Verification example for goo2d."
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  goo2d:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
